### ISSUE TITLE
[Feat]: Match Result Reply with Match Status

### ISSUE THREAD

**Issue by TylerBloom** [MonarchDevelopment/SquireBot#38]
When a match result is entered (and maybe even when its confirmed), the reply should include a match status embed. That way, players know what they are entering/confirming.

**Comment by Ben-Ostrovsky** [comment]
Hi Tyler. I can create a draw instance, if you like. Which file(s) should I look into for this?

**Comment by TylerBloom** [comment]
The changes should be simple. There just needs to be an extra check in `Round::confirm_result`, which is in `round.rs`. This might require adding a new variant in the tournament error. You can add that in `error.rs`.

**Comment by TylerBloom** [comment]
Hi @Ben-Ostrovsky, currently the embed creation for a match (and most things) is not well encapsulated. Currently, the only place that creates match embeds is the match status updater, which used the `update_match_message` function found in `src/utils/embeds.rs`.

The first step would be to separate out the creation of the match embed into its own method or function. It would be helpful to have #40 done for that process. Then, the reply messages for the `match-result` and confirm-result` commands would need to call that new function.
